---
title: "Class12 Lab Session"
author: "Dora Deng"
date: "2025-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1. Proportion of G/G in a population

Downloaded a CSV file from Ensemble <https://useast.ensembl.org/Homo_sapiens/Location/View?db=core;r=17:39901869-39959870;source=dbSNP;v=rs12936231;vdb=variation;vf=959765854;time=1739654652> 

Here we read this CSV file 

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")

head(mxl)
```

```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
table(mxl$Genotype..forward.strand.)/nrow(mxl) * 100
```

Now let's look at a different population. I picked the GBR

```{r}
gbr <- read.csv("373522-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
```

Find proportion of G|G 
```{r}
round(table(gbr$Genotype..forward.strand.)/nrow(gbr) * 100, 2)
```

This varient that is associated with childhood asthma is more frequent in the GBR population than the MKL population. 

Lets now dig into this further. 



